from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/buyer/', views.login_buyer, name='login_buyer'),
    path('login/seller/', views.login_seller, name='login_seller'),
    path('login/delivery/', views.login_delivery, name='login_delivery'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('register/buyer/', views.register_buyer, name='register_buyer'),
    path('register/seller/', views.register_seller, name='register_seller'),
    path('register/delivery/', views.register_delivery, name='register_delivery'),
    path('products/', views.product_list, name='product_list'),
    path('products/<int:pk>/', views.product_detail, name='product_detail'),
    path('seller/dashboard/', views.seller_dashboard, name='seller_dashboard'),
    path('customer/dashboard/', views.customer_dashboard, name='customer_dashboard'),
    path('delivery/dashboard/', views.delivery_dashboard, name='delivery_dashboard'),
    path('delivery/pending/', views.delivery_pending, name='delivery_pending'),
    path('delivery/completed/', views.delivery_completed, name='delivery_completed'),
    path('delivery/profile/', views.delivery_profile, name='delivery_profile'),
    path('delivery/order/<int:pk>/status/', views.update_order_status, name='update_order_status'),
    path('delivery/take_order/<int:order_id>/', views.take_order, name='take_order'),
    path('products/create/', views.product_create, name='product_create'),
    path('products/edit/<int:pk>/', views.product_edit, name='product_edit'),
    path('products/delete/<int:pk>/', views.product_delete, name='product_delete'),
    path('orders/create/', views.create_order, name='create_order'),
    path('orders/history/', views.order_history, name='order_history'),
    path('orders/<int:pk>/', views.order_detail, name='order_detail'),
    path('orders/list/', views.order_list, name='order_list'),
    path('orders/edit/<int:pk>/', views.order_edit, name='order_edit'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/add/', views.category_add, name='category_add'),
    path('wishlist/add/<int:pk>/', views.wishlist_add, name='wishlist_add'),
    path('wishlist/remove/<int:pk>/', views.wishlist_remove, name='wishlist_remove'),
    path('customers/', views.customer_list, name='customer_list'),
    path('profile/', views.customer_profile, name='customer_profile'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('seller/profile/', views.seller_profile, name='seller_profile'),
    path('cart/update/<int:product_id>/', views.update_cart, name='update_cart'),
    path('cart/remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/<int:order_id>/', views.checkout, name='checkout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='auth/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'), name='password_reset_complete'),
    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
    path('address/add/', views.add_address, name='add_address'),
    path('address/delete/<int:pk>/', views.delete_address, name='delete_address'),
    path('address/set_default/<int:pk>/', views.set_default_address, name='set_default_address'),
    path('wishlist/', views.buyer_wishlist, name='buyer_wishlist'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='auth/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='auth/password_change_done.html'), name='password_change_done'),
    path('about/', views.about, name='about'),
    path('spin_wheel/<int:order_id>/', views.spin_wheel, name='spin_wheel'),
    path('buy-now/<int:product_id>/', views.buy_now, name='buy_now'),
    path('contact/', views.contact_us, name='contact_us'),




]