# Generated by Django 5.2.3 on 2025-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_role_deliveryperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)'),
        ),
    ]
