# Generated by Django 5.2.3 on 2025-06-26 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_final_amount_payment_supercoins_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=15),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_spun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='spin_prize',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='supercoin_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='supercoins_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
