# Generated by Django 5.2.3 on 2025-06-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_deliveryperson_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
